# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00bed80884383fbd0fadc425eba19d3d8cdf813dff118b2456863954028365467fb76e65c9c43a594d30bab6c0efb3f9b2005995c76fcaaebf7c2178c1f54e70

test:
  secret_key_base: 79f19cabcae492eaecad5c6bcffd0c201b37a0b20c7136e0df7a5b6856e468f25713a63a183ce9702e52cc410630d540542af317aafc4cb64a18cec2c852c6e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
